### ISSUE TITLE
You didnt put src/lib folder in repo but it exist in video

### ISSUE THREAD

**Issue by IAFahim** [huntabyte/sk-supabase-auth#2]
![image](https://user-images.githubusercontent.com/63500913/211510538-9db8c879-f778-44bc-aab9-d31e583a5818.png)
![image](https://user-images.githubusercontent.com/63500913/211510615-4f6ada47-c8b3-49fa-9e22-93299d623b50.png)

**Comment by delight** [comment]
@IAFahim you are looking at the wrong branch chack final-code or social-dev 😉

**Comment by IAFahim** [comment]
Ehh 🙂 thank you mister youtuber.
