### ISSUE TITLE
how do you make hook.server.ts run even when navigating on the client?

### ISSUE THREAD

**Issue by dongumayagay** [huntabyte/sk-supabase-auth#4]
I have try your tutorial on YT  but I can't make my hook.server run when navigating client side. it only runs on first load or when I reload.

I try to clone this repo and yes the hook.server.ts run when a click a link. i can't replicated that.

I want that so i have a centralize auth guard. for now i use hook.server.ts and root layout.ts but as i have seen on one of your video using root layout load function is not recommended that using hooks is better but i cant make that work.

**Comment by huntabyte** [comment]
@dongumayagay place a +page.server.ts file beside every +page.svelte you want to protect.

**Comment by dongumayagay** [comment]
@huntabyte thanks its working now even with layout.server.ts I don't know why it's currently working with the root layout.server.ts
